services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'pruebaDocker'
      MYSQL_USER: 'Fer'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'Fernan2131'
    volumes:
      # Montamos un volumen para MySQL para no perder
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3306
    platform: linux/x86_64